### PR TITLE
BDS-50 - BSP API - [Dev] Build stubs for integration tests

### PR DESCRIPTION
**Pull request by MartinTGeorgiev**
Remade app to go around commit issues from unknown user. Added unit tests.

### CODE REVIEW

**Review by martin-adaramola — DISMISSED** [review]

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Review by martin-adaramola — APPROVED** [review]

**Review by martin-adaramola — APPROVED** [review]

**Review by martin-adaramola — APPROVED** [review]
All looks good

**Pull request merged**
